# Generated by Django 4.0 on 2021-12-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_team_tier_tier_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.tier'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league'),
        ),
    ]
