# Generated by Django 4.0 on 2021-12-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_team_tier_alter_tier_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='tier',
            name='league',
        ),
    ]
