# Generated by Django 4.0 on 2021-12-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_remove_team_tier_remove_tier_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='league',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='league.league'),
            preserve_default=False,
        ),
    ]
