# Generated by Django 4.0 on 2021-12-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_tier_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='league',
        ),
    ]
