# Generated by Django 4.0 on 2021-12-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_tier_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='field',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='league.venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='tier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='league.tier'),
            preserve_default=False,
        ),
    ]
