# Generated by Django 4.0 on 2021-12-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_team_field_team_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='playoff_series',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tier',
            name='relegations',
            field=models.IntegerField(default=4),
        ),
    ]
