# Generated by Django 4.0 on 2021-12-19 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_alter_team_field_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tier',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.SET_DEFAULT, to='league.tier'),
        ),
        migrations.AlterField(
            model_name='team',
            name='field',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.SET_DEFAULT, to='league.venue'),
        ),
    ]
