# Generated by Django 4.0 on 2021-12-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_alter_table_tier_alter_team_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.tier'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.tier'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.league'),
        ),
        migrations.CreateModel(
            name='TableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.table')),
            ],
        ),
    ]
