# Generated by Django 4.0 on 2021-12-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_alter_table_tier_alter_team_tier_alter_tier_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableentry',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tableentry',
            name='goals_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tableentry',
            name='goals_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tableentry',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tableentry',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tableentry',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tableentry',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('current_day', models.IntegerField(default=0)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.tier')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.schedule')),
            ],
        ),
    ]
