# Generated by Django 4.0 on 2021-12-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_tableentry_draws_tableentry_goals_against_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='tier',
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableentry',
            name='team',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
