# Generated by Django 4.0 on 2021-12-19 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_remove_table_tier_table_name_tableentry_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableentry',
            name='table',
        ),
        migrations.RemoveField(
            model_name='tableentry',
            name='team',
        ),
    ]
