# Generated by Django 4.0 on 2021-12-20 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_remove_tableentry_table_remove_tableentry_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.table'),
        ),
    ]
