# Generated by Django 4.0 on 2021-12-20 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_team_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='table',
        ),
    ]
