# Generated by Django 4.0 on 2021-12-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_remove_team_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableentry',
            name='team_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
