# Generated by Django 4.0 on 2021-12-22 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='tier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='league.tier'),
            preserve_default=False,
        ),
    ]
