# Generated by Django 4.0 on 2021-12-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_table_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableentry',
            name='table',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='league.table'),
            preserve_default=False,
        ),
    ]
