# Generated by Django 4.0 on 2021-12-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_alter_match_options_alter_tableentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
