# Generated by Django 4.0 on 2021-12-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_tier_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='league',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='league.league'),
            preserve_default=False,
        ),
    ]
