# Generated by Django 4.0 on 2021-12-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0025_alter_tier_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='teams',
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='league.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='league.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='league.venue'),
            preserve_default=False,
        ),
    ]
