# Generated by Django 4.0 on 2021-12-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0026_remove_match_teams_match_team1_match_team2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='year',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
