# Generated by Django 4.0 on 2021-12-26 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0029_match_result_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='home_factor',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='luck_factor',
            field=models.DecimalField(decimal_places=1, default=8.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='field',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='league.venue'),
            preserve_default=False,
        ),
    ]
